# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-16 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tindarapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='email',
            new_name='from_email',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='text',
            new_name='message',
        ),
    ]
