# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-16 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tindarapp', '0002_auto_20200516_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='from_email',
            new_name='Email_fra',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='name',
            new_name='Nafn',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='message',
            new_name='Skilabod',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='subject',
            new_name='Titill',
        ),
    ]
