# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-16 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tindarapp', '0003_auto_20200516_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='Email_fra',
            new_name='from_email',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='Skilabod',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='Nafn',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='Titill',
            new_name='subject',
        ),
    ]
